# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed',
            name='rate',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
