# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-08 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_price', models.PositiveIntegerField()),
                ('actual_price', models.PositiveIntegerField()),
                ('last_price', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=64)),
                ('available_time', models.PositiveIntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='food.Food')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='food.Subscribed')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_by', to='food.Subscribed')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodofer',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodofer',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='foodofer',
            name='purchaser',
        ),
        migrations.AlterField(
            model_name='bid',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='done_on', to='food.FoodOffer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='FoodOfer',
        ),
    ]
